/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: cbinet <marvin@42.fr>                      +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2016/12/11 13:27:42 by cbinet            #+#    #+#             */
/*   Updated: 2016/12/19 20:11:16 by cbinet           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "includes/ft_printf.h"
#include <stdio.h> 
#include <locale.h> 
#include <limits.h>
int main()
{
	char* ll = setlocale(LC_ALL, ""); 
	int	i;
	long l;
	char *str;
	wchar_t sstr[] = L"hello";
//	ft_putendl("\n\nmine :");
//	ft_printf("%%d\n%d\n",1234);
//	ft_putendl("printf :");
//	printf("%%d\n%d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%0d\n%0d\n",1234);
//	ft_putendl("printf :");
//	printf("%%0d\n%0d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%06d\n%06d\n",1234);
//	ft_putendl("printf :");
//	printf("%%06d\n%06d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%% 05d\n% 05d\n",1234);
//	ft_putendl("printf :");
//	printf("%% 05d\n% 05d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%+05d\n% 05d\n",1234);
//	ft_putendl("printf :");
//	printf("%%+05d\n% 05d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%+ 05d\n%+ 05d\n",1234);
//	ft_putendl("printf :");
//	printf("%%+ 05d\n%+ 05d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%-5d\n%-5d\n",1234);
//	ft_putendl("printf :");
//	printf("%%-5d\n%-5d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%% +05d\n% +05d\n",1234);
//	ft_putendl("printf :");
//	printf("%% +05d\n% +05d\n",1234);
//	printf("\n\n",1234);
//	printf("%%5d\n%5d\n",1234);
//	ft_printf("%%5d\n%5d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%5.5d\n%5.5d\n",1234);
//	ft_putendl("printf :");
//	printf("%%5.5d\n%5.5d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%5.6d\n%5.6d\n",1234);
//	ft_putendl("printf :");
//	printf("%%5.6d\n%5.6d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%5.4d\n%5.4d\n",1234);
//	ft_putendl("printf :");
//	printf("%%5.4d\n%5.4d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%5.2d\n%5.2d\n",1234);
//	ft_putendl("printf :");
//	printf("%%5.2d\n%5.2d\n",1234);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%5.2s\n%5.2s\n","1234");
//	ft_putendl("printf :");
//	printf("%%5.2s\n%5.2s\n","1234");
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%2s\n%2s\n","1234");
//	ft_putendl("printf :");
//	printf("%%2s\n%2s\n","1234");
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%s\n%s\n","1234");
//	ft_putendl("printf :");
//	printf("%%s\n%s\n","1234");
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%s NULL\n%s\n",NULL);
//	ft_putendl("printf :");
//	printf("%%s NULL\n%s\n", NULL);
//	printf("\n\n",1234);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%55s NULL\n%55s\n",NULL);
//	ft_putendl("printf :");
//	printf("%%55s NULL\n%55s\n", NULL);
//
//
//
//
//	ft_putendl("\n\nmine : ");
//	ft_printf("\n");
//	ft_putendl("printf : ");
//	printf("\n");
//	ft_putendl("\n\nmine : ");
//	ft_printf("%%\n");
//	ft_putendl("printf : ");
//	printf("%%\n");
//	ft_putendl("\n\nmine : ");
//	ft_printf("%d\n", 42);
//	ft_putendl("printf : ");
//	printf("%d\n", 42);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%d%d\n", 42, 41);
//	ft_putendl("printf : ");
//	printf("%d%d\n", 42, 41);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%d%d%d\n", 42, 43, 44);
//	ft_putendl("printf : ");
//	printf("%d%d%d\n", 42, 43, 44);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%ld\n", 2147483647);
//	ft_putendl("printf : ");
//	printf("%ld\n", 2147483647);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%lld\n", 9223372036854775807);
//	ft_putendl("printf : ");
//	printf("%lld\n", 9223372036854775807);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%x\n", 505);
//	ft_putendl("printf : ");
//	printf("%x\n", 505);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%X\n", 505);
//	ft_putendl("printf : ");
//	printf("%X\n", 505);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%p\n", &ft_printf);
//	ft_putendl("printf : ");
//	printf("%p\n", &ft_printf);
//	ft_putendl("\n\nmine : ");
//	ft_printf("% d\n", 3);
//	ft_putendl("printf : ");
//	printf("% d\n", 3);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%+d\n", 3);
//	ft_putendl("printf : ");
//	printf("%+d\n", 3);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%010d\n", 1);
//	ft_putendl("printf : ");
//	printf("%010d\n", 1);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%hhd\n", 0);
//	ft_putendl("printf : ");
//	printf("%hhd\n", 0);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%U\n", 4294967295);
//	ft_putendl("printf : ");
//	printf("%U\n", 4294967295);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%u\n", 4294967295);
//	ft_putendl("printf : ");
//	printf("%u\n", 4294967295);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%o\n", 40);
//	ft_putendl("printf : ");
//	printf("%o\n", 40);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%%#08x\n", 42);
//	ft_putendl("printf : ");
//	printf("%%#08x\n", 42);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%x\n", 1000);
//	ft_putendl("printf : ");
//	printf("%x\n", 1000);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%#X\n", 1000);
//	ft_putendl("printf : ");
//	printf("%#X\n", 1000);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%s\ntest", NULL);
//	ft_putendl("printf : ");
//	printf("%s\n", NULL);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%s%s\n", "test", "test");
//	ft_putendl("printf : ");
//	printf("%s%s\n", "test", "test");
//	ft_putendl("\n\nmine : ");
//	ft_printf("%s%s%s\n", "test", "test", "test");
//	ft_putendl("printf : ");
//	printf("%s%s%s\n", "test", "test", "test");
//	ft_putendl("\n\nmine : ");
//	ft_printf("%p\n", "15000");
//	ft_putendl("printf : ");
//	printf("%p\n", "15000");
//
//	ft_putendl("\n\nmine : ");
//	ft_printf("{cyan}{bgred}%S{eoc}\n", L"ݗݗݜशবݗݜशবݜशব我是฀Ꮺ猫");
//	ft_putendl("printf : ");
//	printf("%S\n", L"ݗݗݜशবݗݜशবݜशব我是฀Ꮺ猫");
//	ft_printf("\n\nle fichier {cyan}%s{eoc}  {bgred}%s{eoc} \n\n", "cyan", "fond rouge" );
// printf("%C", 0);
// ft_printf("%C", 0);
//
//ft_printf("\n\n{black}o {eoc}{red}o {eoc}{green}o {eoc}{yellow}o {eoc}{blue}o {eoc}{pink}o {eoc}{cyan}o {eoc}{grey}o {eoc}{bgblack}o {eoc}{bgred}o {eoc}{bggreen}o {eoc}{bgyellow}o {eoc}{bgblue}o {eoc}{bgpink}o {eoc}{bgcyan}o {eoc}{bggrey}o{eoc}\n\n");
//
//
//
////// UNDONE !!
//	ft_putendl("\n\nmine : ");
//	ft_printf("%20.15d\n", 54321);
//	ft_putendl("printf : ");
//	printf("%20.15d\n", 54321);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%-10d\n", 3);
//	ft_putendl("printf : ");
//	printf("%-10d\n", 3);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%jd\n", 9223372036854775807);
//	ft_putendl("printf : ");
//	printf("%jd\n", 9223372036854775807);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%zd\n", 4294967295);
//	ft_putendl("printf : ");
//	printf("%zd\n", 4294967295);
//	ft_putendl("\n\nmine : ");
//	ft_printf("%\n");
//	ft_putendl("printf : ");
//	printf("%\n");
//	ft_putendl("\n\nmine : ");
//	ft_printf("%C\n", 15000);
//	ft_putendl("printf : ");
//	printf("%C\n", 15000);
//
//
//
//
//	ft_putendl("\n\nmine :");
//	ft_printf("{%s}", 0);
//	ft_putendl("\nprintf :");
//	printf("{%s}", 0);
//	ft_putendl("\n\nmine :");
//	ft_printf("{%s}", "");
//	ft_putendl("\nprintf :");
//	printf("{%s}", "");
//	ft_putendl("\n\nmine :");
//	ft_printf("111%s333%s555", "222", "444");
//	ft_putendl("\nprintf :");
//	printf("111%s333%s555", "222", "444");
//	ft_putendl("\n\nmine :");
//	ft_printf("111%s333%s555%saaa%sccc", "222", "444", "666", "bbb");
//	ft_putendl("\nprintf :");
//	printf("111%s333%s555%saaa%sccc", "222", "444", "666", "bbb");
//	ft_putendl("\n\nmine :");
//	ft_printf("%s%s%s%s%s", "1", "2", "3", "4", "5");
//	ft_putendl("\nprintf :");
//	printf("%s%s%s%s%s", "1", "2", "3", "4", "5");
//	ft_putendl("\n\nmine :");
//	ft_printf("%d", 42);
//	ft_putendl("\nprintf :");
//	printf("%d", 42);
//	ft_putendl("\n\nmine :");
//	ft_printf("%d", -42);
//	ft_putendl("\nprintf :");
//	printf("%d", -42);
//	ft_putendl("\n\nmine :");
//	ft_printf("before %d after", 42);
//	ft_putendl("\nprintf :");
//	printf("before %d after", 42);
//	ft_putendl("\n\nmine :");
//	ft_printf("%d%d%d%d%d", 1, -2, 3, -4, 5);
//	ft_putendl("\nprintf :");
//	printf("%d%d%d%d%d", 1, -2, 3, -4, 5);
//	ft_putendl("\n\nmine :");
//	ft_printf("a%db%dc%dd", 1, -2, 3);
//	ft_putendl("\nprintf :");
//	printf("a%db%dc%dd", 1, -2, 3);
//	ft_putendl("\n\nmine :");
//	ft_printf("%d", INT_MAX);
//	ft_putendl("\nprintf :");
//	printf("%d", INT_MAX);
//	ft_putendl("\n\nmine :");
//	ft_printf("%d", INT_MIN);
//	ft_putendl("\nprintf :");
//	printf("%d", INT_MIN);
//	ft_putendl("\n\nmine :");
//	ft_printf("%p", &i);
//	ft_putendl("\nprintf :");
//	printf("%p", &i);
//	ft_putendl("\n\nmine :");
//	ft_printf("%p", &l);
//	ft_putendl("\nprintf :");
//	printf("%p", &l);
//	ft_putendl("\n\nmine :");
//	ft_printf("%p", &str);
//	ft_putendl("\nprintf :");
//	printf("%p", &str);
//	ft_putendl("\n\nmine :");
//	ft_printf("%p", &strlen);
//	ft_putendl("\nprintf :");
//	printf("%p", &strlen);
//	ft_putendl("\n\nmine :");
//	ft_printf("%p", 0);
//	ft_putendl("\nprintf :");
//	printf("%p", 0);
//	ft_putendl("\n\nmine :");
//	ft_printf("%%");
//	ft_putendl("\nprintf :");
//	printf("%%");
//	ft_putendl("\n\nmine :");
//	ft_printf("aa%%bb");
//	ft_putendl("\nprintf :");
//	printf("aa%%bb");
//	ft_putendl("\n\nmine :");
//	ft_printf("%%%%%%%%%%");
//	ft_putendl("\nprintf :");
//	printf("%%%%%%%%%%");
//	ft_putendl("\n\nmine :");
//	ft_printf(".%%.%%.%%.%%.%%.%%.%%.%%.");
//	ft_putendl("\nprintf :");
//	printf(".%%.%%.%%.%%.%%.%%.%%.%%.");
//	ft_putendl("\n\nmine :");
//	ft_printf("%");
//	ft_putendl("\nprintf :");
//	printf("%");
//	ft_putendl("\n\nmine :");
//	ft_printf("{%}");
//	ft_putendl("\nprintf :");
//	printf("{%}");
//	ft_putendl("\n\nmine :");
//	ft_printf("{% %}");
//	ft_putendl("\nprintf :");
//	printf("{% %}");
	//ft_printf("%lld", LLONG_MIN);
	//printf("%lld", LLONG_MIN);
	ft_printf("%.0p, %.p, %p", 0, 0);
	printf("\n%.0p, %.p, %p", 0, 0);
}
